Backup branch
ELEVATE-Project/data-pipeline pull request #29
Opened 2024-11-22 04:49 UTC by prashanthShiksha

2024-11-23 10:04 UTC, Vivek-M-08 commented
Kindly check the titles of previously closed PRs to ensure this PR title is clear and meaningful.

2024-11-23 10:04 UTC, Vivek-M-08 requested changes

2024-11-24 04:51 UTC, prashanthShiksha commented on metabase-jobs/dashboard-creator/src/main/scala/org/shikshalokam/job/dashboard/creator/functions/MetabaseDashboardFunction.scala
> +    val dashboardData = event.readOrDefault[Map[String, Any]]("dashboardData", Map.empty[String, Any])
resolved

2024-11-24 04:59 UTC, prashanthShiksha commented on metabase-jobs/dashboard-creator/src/main/scala/org/shikshalokam/job/dashboard/creator/functions/MetabaseDashboardFunction.scala
> +              val updateTableQuery = s"UPDATE admin_dashboard_metadata SET status = 'Incomplete',error_message = '${e.getMessage}'  WHERE name = 'Admin';"
done added the logic to check the existance of report based on id and status .
1.if id is present and status is failed then it create the dashboard.
2.if id is present and status is null then it create the dashboard.
3.if id is present and status is success the it throws an exception.
4.if id is not present then it throws an exception.

2024-11-24 16:58 UTC, prashanthShiksha commented on metabase-jobs/dashboard-creator/src/main/scala/org/shikshalokam/job/dashboard/creator/functions/MetabaseDashboardFunction.scala
> +            val updateTableQuery = s"UPDATE admin_dashboard_metadata SET  collection_id = '$collectionId', dashboard_id = '$dashboardId', question_ids = '$questionIdsString', status = 'Completed' WHE
done

2024-11-24 17:04 UTC, prashanthShiksha commented on metabase-jobs/dashboard-creator/src/main/scala/org/shikshalokam/job/dashboard/creator/functions/MetabaseDashboardFunction.scala
> +            addQuestionCards.addQuestionCardsFunction(metabaseUtil, mainDir, dashboardId)
To create the dashboard, we need the complete collection of dashcards. Hence, we are first creating question cards while simultaneously updating the question IDs in the dashcards.

2024-11-24 17:52 UTC, prashanthShiksha commented on metabase-jobs/dashboard-creator/src/main/scala/org/shikshalokam/job/dashboard/creator/functions/MetabaseDashboardFunction.scala
> +      val mainDir: String = "/home/user1/Documents/elevate-data-pipeline3/elevate-data-pipeline/metabase-jobs/dashboard-creator/src/main/scala/org/shikshalokam/job/dashboard/creator/utils/projectJson
done

2024-11-24 17:54 UTC, prashanthShiksha commented on metabase-jobs/dashboard-creator/src/main/scala/org/shikshalokam/job/dashboard/creator/functions/GetTableData.scala
> +  def getTableMetadata(databaseId: Int, metabaseUtil: MetabaseUtil = null, config: MetabaseDashboardConfig): (Int,Int,Int) = {
done

2024-11-24 17:59 UTC, prashanthShiksha commented on metabase-jobs/dashboard-creator/src/main/scala/org/shikshalokam/job/dashboard/creator/functions/UpdateAdminJsonFiles.scala
> +                      val response = metabaseUtil.createQuestionCard(requestBody.toString)
First, we are creating the question cards and then extracting the question IDs, which we are updating in the dashcards.

2024-11-24 18:03 UTC, prashanthShiksha commented on metabase-jobs/dashboard-creator/src/main/scala/org/shikshalokam/job/dashboard/creator/functions/MetabaseDashboardFunction.scala
> +          val parameterFilePath:String = "/home/user1/Documents/elevate-data-pipeline3/elevate-data-pipeline/metabase-jobs/dashboard-creator/src/main/scala/org/shikshalokam/job/dashboard/creator/util
done

2024-11-24 18:03 UTC, prashanthShiksha commented on metabase-jobs/dashboard-creator/src/main/scala/org/shikshalokam/job/dashboard/creator/functions/MetabaseDashboardFunction.scala
> +          val filterFilePath:String = "/home/user1/Documents/elevate-data-pipeline3/elevate-data-pipeline/metabase-jobs/dashboard-creator/src/main/scala/org/shikshalokam/job/dashboard/creator/utils/p
done

2024-11-25 10:27 UTC, prashanthShiksha commented on metabase-jobs/dashboard-creator/src/main/resources/metabase-dashboard.conf
> +  username = "root"
done

2024-11-25 10:29 UTC, prashanthShiksha commented on metabase-jobs/dashboard-creator/src/main/scala/org/shikshalokam/job/dashboard/creator/domain/Event.scala
> +//import scala.jdk.CollectionConverters._  // For Scala 2.13+
done

2024-11-25 10:29 UTC, prashanthShiksha commented on metabase-jobs/dashboard-creator/src/main/scala/org/shikshalokam/job/dashboard/creator/domain/Event.scala
> +  def reportType: String = readOrDefault[String]("reportType", "")
done

2024-11-25 10:30 UTC, prashanthShiksha commented on metabase-jobs/dashboard-creator/src/main/scala/org/shikshalokam/job/dashboard/creator/functions/CreateDashboard.scala
> +    def Get_the_required_ids(CollectionName: String, DashboardName: String, reportType: String, metabaseUtil: MetabaseUtil = null, config: MetabaseDashboardConfig): (Int,Int,Int) = {
done

2024-11-25 10:46 UTC, prashanthShiksha commented on metabase-jobs/dashboard-creator/pom.xml
> +            <groupId>com.typesafe.play</groupId>
I have used these libraries in some parts of the code to make working with JSON files easier.

2024-11-25 11:22 UTC, Vivek-M-08 commented on metabase-jobs/dashboard-creator/src/main/scala/org/shikshalokam/job/dashboard/creator/domain/Event.scala
> +  def reportType: String = readOrDefault[String]("reportType", "")
Can we remove line no 12 if we are not using publishedAt

2024-11-25 11:37 UTC, prashanthShiksha commented on metabase-jobs/dashboard-creator/src/main/scala/org/shikshalokam/job/dashboard/creator/domain/Event.scala
> +  def reportType: String = readOrDefault[String]("reportType", "")
done

2024-11-25 11:51 UTC, Vivek-M-08 commented on metabase-jobs/dashboard-creator/src/main/scala/org/shikshalokam/job/dashboard/creator/functions/UpdateAdminJsonFiles.scala
> +                      val response = metabaseUtil.createQuestionCard(requestBody.toString)
As discussed over a call, this should be addressed. Because you are trying to get all the question Id's and later loping back to the same directory structure to add the question to the dashboard. Even in our old shell scripts, we have the same logic that I mentioned. 

https://github.com/ELEVATE-Project/data-pipeline/blob/dev-deploy/metabase/metabase-scripts/elevate-projects/User-Profile-Based-Reports/04_add_question_cards.sh

2024-11-25 11:52 UTC, prashanthShiksha commented on metabase-jobs/dashboard-creator/src/main/scala/org/shikshalokam/job/dashboard/creator/functions/UpdateStateJsonFiles.scala
> +        updatedJson.transform((__ \ "dataset_query" \ "native" \ "template-tags" \ "state_param").json.prune) match {
I have used these libraries in some parts of the code to make working with JSON files easier.

2024-11-25 11:54 UTC, Vivek-M-08 commented on metabase-jobs/dashboard-creator/src/main/scala/org/shikshalokam/job/dashboard/creator/functions/MetabaseDashboardFunction.scala
> +            addQuestionCards.addQuestionCardsFunction(metabaseUtil, mainDir, dashboardId)
As discussed over a call, this should be addressed. Even in our old shell scripts, we have the same logic that I mentioned.

https://github.com/ELEVATE-Project/data-pipeline/blob/dev-deploy/metabase/metabase-scripts/elevate-projects/User-Profile-Based-Reports/04_add_question_cards.sh

2024-11-25 11:59 UTC, Vivek-M-08 commented on metabase-jobs/dashboard-creator/src/main/scala/org/shikshalokam/job/dashboard/creator/functions/UpdateAdminJsonFiles.scala
> +                      val response = metabaseUtil.createQuestionCard(requestBody.toString)
Understood. We are updating the dash-card section with the question ID.

2024-11-25 12:05 UTC, Vivek-M-08 commented on metabase-jobs/dashboard-creator/src/main/scala/org/shikshalokam/job/dashboard/creator/functions/MetabaseDashboardFunction.scala
> +          val filterFilePath:String = "/home/user1/Documents/elevate-data-pipeline3/elevate-data-pipeline/metabase-jobs/dashboard-creator/src/main/scala/org/shikshalokam/job/dashboard/creator/utils/p
Why can't we just append `/state-parameter.json` to the existing `mainDirAbsolutePath` variable which will be the same as you added?

```
val parameterFilePath: String = "metabase-jobs/dashboard-creator/src/main/scala/org/shikshalokam/job/dashboard/creator/utils/projectJson/admin-parameter.json"
val parameterFileAbsPath: String = new java.io.File(parameterFilePath).getCanonicalPath           
```

2024-11-25 12:09 UTC, Vivek-M-08 commented on metabase-jobs/dashboard-creator/src/main/scala/org/shikshalokam/job/dashboard/creator/functions/MetabaseDashboardFunction.scala
> +          val parameterFilePath:String = "/home/user1/Documents/elevate-data-pipeline3/elevate-data-pipeline/metabase-jobs/dashboard-creator/src/main/scala/org/shikshalokam/job/dashboard/creator/util
Why can't we just append /admin-parameter.json to the existing mainDirAbsolutePath variable which will be the same as what you have added?

```
val parameterFilePath: String = "metabase-jobs/dashboard-creator/src/main/scala/org/shikshalokam/job/dashboard/creator/utils/projectJson/admin-parameter.json"
val parameterFileAbsPath: String = new java.io.File(parameterFilePath).getCanonicalPath
```

2024-11-25 12:12 UTC, Vivek-M-08 commented on metabase-jobs/dashboard-creator/pom.xml
> +            <groupId>com.typesafe.play</groupId>
Can we not archive the same with `com.fasterxml.jackson.core` dependency?

2024-11-25 12:19 UTC, prashanthShiksha commented on metabase-jobs/dashboard-creator/src/main/scala/org/shikshalokam/job/dashboard/creator/functions/MetabaseDashboardFunction.scala
> +    if (event.reportType == "Project") {
done

2024-11-25 12:42 UTC, prashanthShiksha commented on metabase-jobs/dashboard-creator/src/main/scala/org/shikshalokam/job/dashboard/creator/functions/UpdateStateJsonFiles.scala
> +  def ProcessAndUpdateJsonFiles(mainDir: String, dashboardId: BigInt, collectionId: BigInt, databaseId: BigInt, statenameId: BigInt, districtnameId: BigInt, programnameId: BigInt, metabaseUtil: Metab
done

2024-11-25 13:09 UTC, prashanthShiksha commented on metabase-jobs/dashboard-creator/src/main/scala/org/shikshalokam/job/dashboard/creator/functions/MetabaseDashboardFunction.scala
> +          val filterFilePath:String = "/home/user1/Documents/elevate-data-pipeline3/elevate-data-pipeline/metabase-jobs/dashboard-creator/src/main/scala/org/shikshalokam/job/dashboard/creator/utils/p
done

2024-11-25 13:09 UTC, prashanthShiksha commented on metabase-jobs/dashboard-creator/src/main/scala/org/shikshalokam/job/dashboard/creator/functions/MetabaseDashboardFunction.scala
> +          val parameterFilePath:String = "/home/user1/Documents/elevate-data-pipeline3/elevate-data-pipeline/metabase-jobs/dashboard-creator/src/main/scala/org/shikshalokam/job/dashboard/creator/util
done

2024-11-25 13:15 UTC, prashanthShiksha commented on metabase-jobs/dashboard-creator/src/main/scala/org/shikshalokam/job/dashboard/creator/functions/MetabaseDashboardFunction.scala
> +            val questionCardIdList = UpdateAdminJsonFiles.ProcessAndUpdateJsonFiles(mainDir = mainDir, dashboardId = dashboardId, collectionId = collectionId, databaseId = databaseId, statenameId = s
done

2024-11-25 13:30 UTC, prashanthShiksha commented on metabase-jobs/dashboard-creator/src/main/scala/org/shikshalokam/job/dashboard/creator/functions/MetabaseDashboardFunction.scala
> +            val parameterFilePath:String = "/home/user1/Documents/elevate-data-pipeline3/elevate-data-pipeline/metabase-jobs/dashboard-creator/src/main/scala/org/shikshalokam/job/dashboard/creator/ut
what should be done here ?

2024-11-25 13:53 UTC, prashanthShiksha commented on metabase-jobs/dashboard-creator/src/main/scala/org/shikshalokam/job/dashboard/creator/functions/MetabaseDashboardFunction.scala
> +            addQuestionCards.addQuestionCardsFunction(metabaseUtil, mainDir, dashboardId)
There are a total of 24 questions. Previously, we were calling the existing dashboard API response for each question card and then appending the dashcards, which meant the API was called 24 times.
Here’s what I did: I collected all the dashcards at once and then created the dashboard using the dashboard API.

2024-11-27 12:48 UTC, Vivek-M-08 requested changes

2024-11-27 12:48 UTC, Vivek-M-08 commented on metabase-jobs/dashboard-creator/src/main/scala/org/shikshalokam/job/dashboard/creator/functions/MetabaseDashboardFunction.scala
> +            val collectionName = s"State Collection [1]"
Change the collectionName and dashboardName to store the state name

2024-11-27 12:50 UTC, Vivek-M-08 commented on metabase-jobs/dashboard-creator/src/main/scala/org/shikshalokam/job/dashboard/creator/functions/MetabaseDashboardFunction.scala
> +          val parameterFilePath:String = "/home/user1/Documents/elevate-data-pipeline3/elevate-data-pipeline/metabase-jobs/dashboard-creator/src/main/scala/org/shikshalokam/job/dashboard/creator/util
@prashanthShiksha—This is not working while we deploy it in the dev environment because it is trying to read the path from where this job is being submitted instead of the JSON file path.

2024-11-27 12:51 UTC, Vivek-M-08 commented on metabase-jobs/dashboard-creator/src/main/scala/org/shikshalokam/job/dashboard/creator/functions/MetabaseDashboardFunction.scala
> +          val filterFilePath:String = "/home/user1/Documents/elevate-data-pipeline3/elevate-data-pipeline/metabase-jobs/dashboard-creator/src/main/scala/org/shikshalokam/job/dashboard/creator/utils/p
This is not working while we deploy it in the dev environment because it is trying to read the path from where this job is being submitted instead of the JSON file path.

2024-11-28 05:02 UTC, prashanthShiksha commented on metabase-jobs/dashboard-creator/src/main/scala/org/shikshalokam/job/dashboard/creator/functions/MetabaseDashboardFunction.scala
> +            val collectionName = s"State Collection [1]"
done

2024-11-28 05:02 UTC, prashanthShiksha commented on metabase-jobs/dashboard-creator/src/main/scala/org/shikshalokam/job/dashboard/creator/functions/GetTableData.scala
> +object GetTableData {
done

2024-11-28 05:08 UTC, prashanthShiksha commented on metabase-jobs/dashboard-creator/src/main/scala/org/shikshalokam/job/dashboard/creator/functions/MetabaseDashboardFunction.scala
> +            val CollectionQuery = s"UPDATE admin_dashboard_metadata SET status = 'Failed',error_message = 'errorMessage'  WHERE name = '$admin';"
done

2024-11-28 05:08 UTC, prashanthShiksha commented on metabase-jobs/dashboard-creator/src/main/scala/org/shikshalokam/job/dashboard/creator/functions/MetabaseDashboardFunction.scala
> +              val CollectionQuery = s"UPDATE admin_dashboard_metadata SET status = 'Failed',error_message = 'errorMessage'  WHERE name = '$admin';"
done

2024-11-28 05:10 UTC, prashanthShiksha commented on metabase-jobs/dashboard-creator/src/main/scala/org/shikshalokam/job/dashboard/creator/functions/MetabaseDashboardFunction.scala
> +              val collectionId : Int = CreateDashboard.checkAndCreateCollection(collectionName = collectionName, ReportType = "Project", metabaseUtil = metabaseUtil, postgresUtil = postgresUtil,metaT
done

2024-11-28 05:20 UTC, prashanthShiksha commented on metabase-jobs/dashboard-creator/src/main/scala/org/shikshalokam/job/dashboard/creator/functions/addQuestionCards.scala
> +object addQuestionCards {
done

2024-11-28 05:20 UTC, prashanthShiksha commented on metabase-jobs/dashboard-creator/src/main/scala/org/shikshalokam/job/dashboard/creator/functions/CreateDashboard.scala
> +    def checkAndCreateCollection(collectionName: String,ReportType: String, metabaseUtil: MetabaseUtil, postgresUtil: PostgresUtil,metaTableQuery:String): Int = {
done

2024-11-28 05:29 UTC, prashanthShiksha commented on metabase-jobs/dashboard-creator/src/main/scala/org/shikshalokam/job/dashboard/creator/functions/MetabaseDashboardFunction.scala
> +          val AdminIdCheckQuery: String = s"SELECT CASE WHEN EXISTS (SELECT 1 FROM admin_dashboard_metadata WHERE name = '$admin') THEN CASE WHEN COALESCE((SELECT status FROM admin_dashboard_metadata
done

2024-11-28 05:31 UTC, prashanthShiksha commented on metabase-jobs/dashboard-creator/src/main/scala/org/shikshalokam/job/dashboard/creator/functions/CreateDashboard.scala
> +                     |  "description": "Collection for $ReportType reports"
are we creating surveys and observation reports under same collection ?

2024-12-02 04:47 UTC, prashanthShiksha commented on metabase-jobs/dashboard-creator/pom.xml
> +            <groupId>com.typesafe.play</groupId>
resolved

2024-12-02 04:48 UTC, prashanthShiksha commented on metabase-jobs/dashboard-creator/src/main/scala/org/shikshalokam/job/dashboard/creator/functions/MetabaseDashboardFunction.scala
> +            addQuestionCards.addQuestionCardsFunction(metabaseUtil, mainDir, dashboardId)
done

2024-12-02 04:48 UTC, prashanthShiksha commented on metabase-jobs/dashboard-creator/src/main/scala/org/shikshalokam/job/dashboard/creator/functions/MetabaseDashboardFunction.scala
> +          val parameterFilePath:String = "/home/user1/Documents/elevate-data-pipeline3/elevate-data-pipeline/metabase-jobs/dashboard-creator/src/main/scala/org/shikshalokam/job/dashboard/creator/util
done

2024-12-02 04:49 UTC, prashanthShiksha commented on metabase-jobs/dashboard-creator/src/main/scala/org/shikshalokam/job/dashboard/creator/functions/MetabaseDashboardFunction.scala
> +          val filterFilePath:String = "/home/user1/Documents/elevate-data-pipeline3/elevate-data-pipeline/metabase-jobs/dashboard-creator/src/main/scala/org/shikshalokam/job/dashboard/creator/utils/p
done

2024-12-02 04:49 UTC, prashanthShiksha commented on metabase-jobs/dashboard-creator/src/main/scala/org/shikshalokam/job/dashboard/creator/functions/UpdateStateJsonFiles.scala
> +        updatedJson.transform((__ \ "dataset_query" \ "native" \ "template-tags" \ "state_param").json.prune) match {
done

2024-12-02 05:13 UTC, Vivek-M-08 commented on metabase-jobs/dashboard-creator/src/main/scala/org/shikshalokam/job/dashboard/creator/functions/CreateDashboard.scala
> +                     |  "description": "Collection for $ReportType reports"
Yes, If there is a KA state collection it can hold surveys, observations and project reports. If not we will have to create 3 KA state collection for each one report.

2024-12-02 12:24 UTC, Vivek-M-08 commented on metabase-jobs/dashboard-creator/src/main/scala/org/shikshalokam/job/dashboard/creator/functions/MetabaseDashboardFunction.scala
> +            val parameterFilePath:String = "/home/user1/Documents/elevate-data-pipeline3/elevate-data-pipeline/metabase-jobs/dashboard-creator/src/main/scala/org/shikshalokam/job/dashboard/creator/ut
This has been addressed.

2024-12-02 12:31 UTC, Vivek-M-08 commented on metabase-jobs/dashboard-creator/src/main/scala/org/shikshalokam/job/dashboard/creator/functions/MetabaseDashboardFunction.scala
> +          val AdminIdCheckQuery: String = s"SELECT CASE WHEN EXISTS (SELECT 1 FROM admin_dashboard_metadata WHERE name = '$admin') THEN CASE WHEN COALESCE((SELECT status FROM admin_dashboard_metadata
Still, AdminIdCheckQuery and AdminIdStatus are not in camel-case.

2024-12-02 12:38 UTC, Vivek-M-08 commented on metabase-jobs/dashboard-creator/src/main/scala/org/shikshalokam/job/dashboard/creator/functions/UpdateStateJsonFiles.scala
> +  def ProcessAndUpdateJsonFiles(mainDir: String, dashboardId: BigInt, collectionId: BigInt, databaseId: BigInt, statenameId: BigInt, districtnameId: BigInt, programnameId: BigInt, metabaseUtil: Metab
This is updated

2024-12-04 09:41 UTC, Vivek-M-08 requested changes

2024-12-04 13:09 UTC, prashanthShiksha commented on metabase-jobs/dashboard-creator/src/main/scala/org/shikshalokam/job/dashboard/creator/functions/MetabaseDashboardFunction.scala
> +          val parameterFilePath:String = "/home/user1/Documents/elevate-data-pipeline3/elevate-data-pipeline/metabase-jobs/dashboard-creator/src/main/scala/org/shikshalokam/job/dashboard/creator/util
yes

2024-12-04 13:09 UTC, prashanthShiksha commented on metabase-jobs/dashboard-creator/src/main/scala/org/shikshalokam/job/dashboard/creator/functions/MetabaseDashboardFunction.scala
> +          val AdminIdCheckQuery: String = s"SELECT CASE WHEN EXISTS (SELECT 1 FROM admin_dashboard_metadata WHERE name = '$admin') THEN CASE WHEN COALESCE((SELECT status FROM admin_dashboard_metadata
done

2024-12-04 13:28 UTC, prashanthShiksha commented on metabase-jobs/dashboard-creator/src/main/scala/org/shikshalokam/job/dashboard/creator/functions/CreateDashboard.scala
> +                     |  "description": "Collection for $ReportType reports"
changed to 
collection For Admin Report
collection For state report [Karnataka]
collection For District report [Bangalore South - Karnataka]
collection For Program report [DCPCR]

2024-12-04 13:28 UTC, prashanthShiksha commented on metabase-jobs/dashboard-creator/src/main/scala/org/shikshalokam/job/dashboard/creator/functions/MetabaseDashboardFunction.scala
> +              val updateTableQuery = s"UPDATE program_dashboard_metadata SET status = 'Failed',error_message = '${e.getMessage}'  WHERE id = '$targetedProgramId';"
done

2024-12-05 13:57 UTC, Vivek-M-08 commented on metabase-jobs/dashboard-creator/src/main/scala/org/shikshalokam/job/dashboard/creator/functions/UpdateAdminJsonFiles.scala
> +object UpdateAdminJsonFiles {
resolved

2024-12-06 05:36 UTC, merged